### ISSUE TITLE
cannot compile using Delphi 2007

### ISSUE THREAD

**Issue by mredlancelot** [Hugie/lz4-delphi#7]
after modifying the uses clauses as this version of delphi doesnt have the full namespace qualifiers, everything sems OK except that the te4st project does not compile with the error:

[DCC Error] lz4d.dependencies.pas(130): E2045 Bad object file format: 'C:\Users\esilva\Downloads\lz4-delphi-master\lz4-delphi-master\lib/win32_mingw/chkstk_ms.o'

any ideas?

I am using Delphi 2007 Pro, Win32.

**Comment by Hugie** [comment]
Sorry, i have not tested it with Delphi 2007. I can only compile with >=XE3.
There are a lot of problems with object files and delphi. I opened a bug report at embarcadero for a other object file related problem and the result was: "we know, it won't get fixed. Object file support is limited".

Sorry, i can not help you with this.

**Comment by mredlancelot** [comment]
I understand... thank you for your quick response.

**Comment by Hugie** [comment]
I asked a question related to this on stackoverflow: https://stackoverflow.com/questions/28626397 . Maybe it helps you a bit more with the objcet file format problem.

**Comment by Hugie** [comment]
Maybe you can convert the object files to the necessary format using "coff2omf" as suggested at different places or give this object converter a try: http://agner.org/optimize/#objconv

**Comment by mredlancelot** [comment]
We are currently in the process of migrating to XE7, so I'll resume this when this is done, thank you for your efforts.
